"""empty message

Revision ID: 05a6e636fc94
Revises: 6c581eeeab54
Create Date: 2024-02-14 23:08:34.148439

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '05a6e636fc94'
down_revision = '6c581eeeab54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
