"""Add payment breakdown to order

Revision ID: 0a1bb047dcde
Revises: b54799f5391b
Create Date: 2024-12-31 19:29:30.537614

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a1bb047dcde'
down_revision = 'b54799f5391b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('payment_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'payment_breakdown')
    # ### end Alembic commands ###
