"""Add payment_breakdown to cart

Revision ID: 0cb03e43fb58
Revises: 0a1bb047dcde
Create Date: 2025-01-01 00:24:23.872827

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0cb03e43fb58'
down_revision = '0a1bb047dcde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('payment_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'payment_breakdown')
    # ### end Alembic commands ###
