"""Add currency symbol

Revision ID: 14ecb5affd89
Revises: 4dbc17dd3699
Create Date: 2024-12-31 10:28:27.293103

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '14ecb5affd89'
down_revision = '4dbc17dd3699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE currency SET symbol = '' WHERE symbol IS NULL")
    op.alter_column('currency', 'symbol', nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency', 'symbol')
    # ### end Alembic commands ###
