"""empty message

Revision ID: 2045879a3ad4
Revises: d1f8924753e7
Create Date: 2024-03-04 20:03:26.924866

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2045879a3ad4'
down_revision = 'd1f8924753e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('ordered_product_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'ordered_product_data')
    # ### end Alembic commands ###
