"""empty message

Revision ID: 21ef8dcd5ce7
Revises: 727ed64cfe07
Create Date: 2024-03-12 17:46:11.222112

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '21ef8dcd5ce7'
down_revision = '727ed64cfe07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
