"""empty message

Revision ID: 2b18b7bcdd92
Revises: f9c444f939ad
Create Date: 2024-03-11 20:00:07.038195

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2b18b7bcdd92'
down_revision = 'f9c444f939ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
