"""empty message

Revision ID: 357983b52018
Revises: b5445a5eaba4
Create Date: 2024-04-05 22:40:06.671750

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '357983b52018'
down_revision = 'b5445a5eaba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('shipments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('order', 'shipment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('shipment', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('order', 'shipments')
    # ### end Alembic commands ###
