"""Add product preorder

Revision ID: 3ddd607983a5
Revises: 73abe9e30f6f
Create Date: 2024-12-14 16:39:26.354559

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3ddd607983a5'
down_revision = '73abe9e30f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('preorder', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    op.alter_column('product', 'preorder', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'preorder')
    # ### end Alembic commands ###
