"""empty message

Revision ID: 4fbbf65bccd2
Revises: 2911f7cceee1
Create Date: 2024-02-09 22:50:00.615193

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4fbbf65bccd2'
down_revision = '2911f7cceee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
