"""Add shipping/order/cart links

Revision ID: 6c3228e39f64
Revises: d7cd29ce0a23
Create Date: 2024-12-25 21:09:45.087820

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6c3228e39f64'
down_revision = 'd7cd29ce0a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('shipping_rate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart', 'shippingrate', ['shipping_rate_id'], ['id'])
    op.add_column('order', sa.Column('shipping_rate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'shippingrate', ['shipping_rate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'shipping_rate_id')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'shipping_rate_id')
    # ### end Alembic commands ###
