"""empty message

Revision ID: 6c581eeeab54
Revises: d98d05d36ae7
Create Date: 2024-02-14 23:03:06.032282

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6c581eeeab54'
down_revision = 'd98d05d36ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_category_ids_fkey', 'product', type_='foreignkey')
    op.drop_column('product', 'category_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_ids', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('product_category_ids_fkey', 'product', 'category', ['category_ids'], ['id'])
    # ### end Alembic commands ###
