"""Add shipping_rate_data to cart and order

Revision ID: 76e67c69e8bf
Revises: 6c3228e39f64
Create Date: 2024-12-29 16:28:28.961224

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76e67c69e8bf'
down_revision = '6c3228e39f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('shipping_rate_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('order', sa.Column('shipping_rate_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'shipping_rate_data')
    op.drop_column('cart', 'shipping_rate_data')
    # ### end Alembic commands ###
