"""Add refunds

Revision ID: 9c6b17288030
Revises: 9e5aa3798cd0
Create Date: 2024-12-22 22:50:37.939169

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c6b17288030'
down_revision = '9e5aa3798cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('refunds', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'refunds')
    # ### end Alembic commands ###
