"""empty message

Revision ID: a36cda77ba80
Revises: c811f6d64605
Create Date: 2024-02-14 16:01:17.956940

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a36cda77ba80'
down_revision = 'c811f6d64605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'product_id')
    # ### end Alembic commands ###
