"""empty message

Revision ID: c26596c5c5ec
Revises: 4fbbf65bccd2
Create Date: 2024-02-09 23:13:56.723792

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c26596c5c5ec'
down_revision = '4fbbf65bccd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
