"""empty message

Revision ID: c36978e0fac0
Revises: e2fc10897485
Create Date: 2024-02-19 23:03:36.776492

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c36978e0fac0'
down_revision = 'e2fc10897485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('quantity', sa.Integer(), nullable=True))
    op.execute("UPDATE product SET quantity = 4")
    op.alter_column('product', 'quantity', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'quantity')
    # ### end Alembic commands ###
