"""empty message

Revision ID: cb849e6771d0
Revises: a36cda77ba80
Create Date: 2024-02-14 22:32:48.925489

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cb849e6771d0'
down_revision = 'a36cda77ba80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('product_ids', sa.Integer(), nullable=True))
    op.drop_constraint('category_product_id_fkey', 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'product', ['product_ids'], ['id'])
    op.drop_column('category', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key('category_product_id_fkey', 'category', 'product', ['product_id'], ['id'])
    op.drop_column('category', 'product_ids')
    # ### end Alembic commands ###
