"""Add product package dimensions

Revision ID: d7cd29ce0a23
Revises: ea84e4bb48a0
Create Date: 2024-12-25 18:06:04.323338

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd7cd29ce0a23'
down_revision = 'ea84e4bb48a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('package_dimensions', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'package_dimensions')
    # ### end Alembic commands ###
