"""empty message

Revision ID: d98d05d36ae7
Revises: cb849e6771d0
Create Date: 2024-02-14 22:38:29.579255

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd98d05d36ae7'
down_revision = 'cb849e6771d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_product_ids_fkey', 'category', type_='foreignkey')
    op.drop_column('category', 'product_ids')
    op.add_column('product', sa.Column('category_ids', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'category', ['category_ids'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'category_ids')
    op.add_column('category', sa.Column('product_ids', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('category_product_ids_fkey', 'category', 'product', ['product_ids'], ['id'])
    # ### end Alembic commands ###
