"""Add name_musnad to product

Revision ID: dfddc66e6a3b
Revises: ff91c0d1cc7a
Create Date: 2025-01-02 16:53:03.350423

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dfddc66e6a3b'
down_revision = 'ff91c0d1cc7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('name_musnad', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'name_musnad')
    # ### end Alembic commands ###
