"""empty message

Revision ID: e391e3a6a801
Revises: d0529a659d5f
Create Date: 2024-02-20 22:02:19.570229

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e391e3a6a801'
down_revision = 'd0529a659d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customer', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customer', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
