"""Add service_name, delivery_time, cost

Revision ID: ea84e4bb48a0
Revises: 63114a7182ca
Create Date: 2024-12-24 21:11:51.278701

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ea84e4bb48a0'
down_revision = '63114a7182ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shippingrate', sa.Column('service_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('shippingrate', sa.Column('delivery_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('shippingrate', sa.Column('cost', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shippingrate', 'cost')
    op.drop_column('shippingrate', 'delivery_time')
    op.drop_column('shippingrate', 'service_name')
    # ### end Alembic commands ###
