"""empty message

Revision ID: ee9378691c4d
Revises: 13ae0edf86a9
Create Date: 2024-02-14 01:51:41.315778

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ee9378691c4d'
down_revision = '13ae0edf86a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('material', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('product', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('size', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE product SET material = 'temp'")
    op.alter_column('product', 'material', nullable=False)
    op.execute("UPDATE product SET weight = 0.00")
    op.alter_column('product', 'weight', nullable=False)
    op.execute("UPDATE product SET size = 'temp'")
    op.alter_column('product', 'size', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'size')
    op.drop_column('product', 'weight')
    op.drop_column('product', 'material')
    # ### end Alembic commands ###
