"""empty message

Revision ID: f9c444f939ad
Revises: 2045879a3ad4
Create Date: 2024-03-11 18:36:59.422972

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f9c444f939ad'
down_revision = '2045879a3ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productcartlink', sa.Column('cart_quantity', sa.Integer(), nullable=True))
    op.add_column('productorderlink', sa.Column('order_quantity', sa.Integer(), nullable=True))
    op.execute("UPDATE productcartlink SET cart_quantity = 1")
    op.alter_column('productcartlink', 'cart_quantity', nullable=False)
    op.execute("UPDATE productorderlink SET order_quantity = 1")
    op.alter_column('productorderlink', 'order_quantity', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productorderlink', 'order_quantity')
    op.drop_column('productcartlink', 'cart_quantity')
    # ### end Alembic commands ###
