"""empty message

Revision ID: fc28e69985a8
Revises: e391e3a6a801
Create Date: 2024-02-22 17:50:39.169188

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc28e69985a8'
down_revision = 'e391e3a6a801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'payment')

    op.add_column('order', sa.Column('payment', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'payment')

    op.add_column('order', sa.Column('payment', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###