"""Add featured to product

Revision ID: ff91c0d1cc7a
Revises: 5a4fc76624ef
Create Date: 2025-01-02 16:20:29.162795

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ff91c0d1cc7a'
down_revision = '5a4fc76624ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'featured')
    # ### end Alembic commands ###
